### ISSUE TITLE
Voice API `callTo` Parameter Only Initiates Call to Last Number in Array

### ISSUE THREAD

**Issue by oxenprogrammer** [AfricasTalkingLtd/africastalking-node.js#111]
### Issue Description
The `Voice API` currently specifies the `CallTo` parameter as an array of phone numbers in comma-separated string format, which can be passed to the options object as shown below:

```javascript
 const options = {
      callFrom: "+256******", // Set your Africa's Talking phone number in international format
      callTo: ["+2567*******", "+256*******"], // Set the numbers you want to call to in a comma-separated list
    };
```

However, when initiating a call, it appears that the API is only dialing the last number in the array, rather than calling all the numbers as expected.

### Expected Behavior
The expected behavior is for the `callTo` parameter to facilitate calling all the numbers listed in the array, ensuring that each number in the list receives a call.

**Comment by SamuelMwangiW** [comment]
Hi @oxenprogrammer 

As indicated in the [README](https://github.com/AfricasTalkingLtd/africastalking-node.js#voiceservice), the callTo parameter should be a string and not an Array.

https://github.com/AfricasTalkingLtd/africastalking-node.js/blob/master/README.md?plain=1#L201-L205

**Comment by oxenprogrammer** [comment]
@SamuelMwangiW I could push a fix but I also created an issue [here](https://github.com/AfricasTalkingLtd/africastalking-node.js/issues/112) on  community `Contribution Guidelines` as a I couldn't get one.

**Comment by SamuelMwangiW** [comment]
> @SamuelMwangiW I could push a fix but I also created an issue [here](https://github.com/AfricasTalkingLtd/africastalking-node.js/issues/112) on community `Contribution Guidelines` as a I couldn't get one.

@DaggieBlanqx kindly advise

**Comment by oxenprogrammer** [comment]
@DaggieBlanqx is anything going to get done here?
Actually this whole thing doesn't work in version `0.6.2`, it works on `0.5.5`.
Is there a problem with the call API?

**Comment by DaggieBlanqx** [comment]
Hello @oxenprogrammer, we are fixing this. Thank you for your patience.
