### ISSUE TITLE
node v5

### ISSUE THREAD

**Issue by ianjuma** [AfricasTalkingLtd/africastalking-node.js#12]
node v5 advisory on the README? I think we'll just make the move this early and ignore the es5 branch.

and just maybe have this instead:

### Ubuntu

```bash
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install -y nodejs
```

### Other platforms
https://nodejs.org/en/download/package-manager/

are we shooting for backward compatibility?

**Comment by pbombo** [comment]
Hmmm maybe a working with the LTS version of node [v4](https://nodejs.org/en/blog/release/v4.2.0/) might be the way to go before _jumping_ into node v5?

**Comment by aksalj** [comment]
@pbombo Agreed! However, it seems to me that many production environments are still using either `0.10` or `0.12`(just an observation I have made, got no data to back it up :hear_no_evil:)

**Comment by ianjuma** [comment]
ok, this is the issue, I don't understand it that well; but is node V5 fully compatible with previous versions; is there a problem with jumping here? do some libs fail to build on the ES6 branch?

**Comment by pbombo** [comment]
@aksalj I think you are right, lots of people are v0.1.x node but the current LTS version of node is v4.x

@ianjuma there are some challenges while backporting modules that are designed to work with v5.x with 0.1.x particularly with regards to ES6 features. 

I think a moving straight to v4 might be the only option even though it may come with pain points...

**Comment by ianjuma** [comment]
If this works with v4.x LTS or 5.x and 6.x LTS - I think we'll be fine. I'm proceeding to close this issue.
