### ISSUE TITLE
SMS Message With A Different String Font Being Sent in a Cryptic Manner

### ISSUE THREAD

**Issue by kiwavi** [AfricasTalkingLtd/africastalking-node.js#125]
Hello, 

How does the SMS service deal with different fonts? When i use certain fonts, the message that's sent is in a different form. Some fonts are seemingly being parsed/escaped by ATs validation layer such that a string like 𝗛𝗲𝗹𝗹𝗼 is sent as d  'd  2d  1d  1d. How can I solve this? Using nodeJS for the backend

**Comment by aksalj** [comment]
Hey @kiwavi,

SMS does not support "fonts". Your "font" information will simply be encoded as unicode characters or something similar
