### ISSUE TITLE
Promise Error

### ISSUE THREAD

**Issue by denzelwamburu** [AfricasTalkingLtd/africastalking-node.js#13]
Great Library :smiley: 
Though am running into an error when trying to send a simple sms. Seems to be something when returning a promise.
Here is the error
`.then(function(s) { `
  `  ^`

`TypeError: Cannot read property 'then' of undefined`
Code:
`  var AfricasTalking = require('africastalking')(options);`
  `  var sms = AfricasTalking.SMS;`
    `var opts = {`
     ` to: 0704654445,`
      `message: 'Server is Running' `
    `};`
   ` console.log(opts);`

 `   sms.send(opts)`
 `   .then(function(s) {`
`        console.log(s);`
   `  })`
   `   .catch(function(error) {`
`        console.log(error);`
     ` }); `

**Comment by pbombo** [comment]
The issue is that your number is not a string and in the format `+2547xxxxxxx`

@aksalj or @ianjuma :) need to fix the error message for when you have an invalid number format

**Comment by aksalj** [comment]
This error (`TypeError: Cannot read property then of undefined`) should not occur even with the non-string `to` value because [this](https://github.com/AfricasTalkingLtd/africastalking-node.js/blob/master/lib/sms.js#L23-L59) is checking it and is supposed to throw an [exception](https://github.com/AfricasTalkingLtd/africastalking-node.js/blob/master/lib/sms.js#L90-L92) instead...

@pbombo yeah it should show a clear message instead of just throwing a generic error!

**Comment by denzelwamburu** [comment]
@pbombo Even after using the format '+2547xxxxxxx', the error still persists

**Comment by aksalj** [comment]
@denzelwamburu what version of the library and `node` are you using?

Also when I replicate your code above like this
```javascript
var AfricasTalking = require ('africastalking')({apiKey:null, username: null, format: "json"});
var sms = AfricasTalking.SMS;
var opts = {
    to: 0704654445,
    message: 'Server is Running'
};
console.log(opts);

sms.send(opts)
    .then(function(s) {
        console.log(s);
    })
    .catch(function(error) {
        console.log(error);
    });
```
here is what I (and should) get
```shell
TheWhiteRock:afticastalking aksalj$ node index.js 

/Users/aksalj/src/playground/afticastalking/node_modules/africastalking/lib/index.js:43
        throw error;
        ^
[object Object]
TheWhiteRock:afticastalking aksalj$ 
```

Like @pbombo said, `opts.to` needs to be a **string** like `"254704654445"` and not a number like `254704654445`.

**Comment by denzelwamburu** [comment]
Hey @aksalj am on node `v5.4.1`.
Still using that string format still throws the same error.
Apparently am using loopback, but when using express `v4.13.1` throws the error you are getting.
Could it be the node version?

**Comment by aksalj** [comment]
@denzelwamburu Ideally, it should not matter what framework you use. And any node version `>= 0.12` should work fine.
Currently (`v0.0.2`), `AfricasTalking.SMS.send()` either [thows](https://github.com/AfricasTalkingLtd/africastalking-node.js/blob/master/lib/sms.js#L91) an exception or always returns a [promise](https://github.com/AfricasTalkingLtd/africastalking-node.js/blob/master/lib/sms.js#L106); so this `TypeError: Cannot read property 'then' of undefined` should not occur. 

Is it possible to show the actual code where you are getting this error?

**Comment by denzelwamburu** [comment]
@aksalj i updated the library to version `0.0.2`.
Works fine Now. :)
![at](https://cloud.githubusercontent.com/assets/6532631/14199491/870b6ed2-f7ed-11e5-8cc3-d8dbf2a3b9a3.png)
