### ISSUE TITLE
Validation throws errors should not throw errors outside promise

### ISSUE THREAD

**Issue by habbes** [AfricasTalkingLtd/africastalking-node.js#16]
I noticed in SMS.send and other api wrapper methods you're calling _validateParams() outside the Promise wrapper and throwing an error. This means the user has to wrap the method call in try-catch block to prevent a crash but still has to check for other errors using the catch() hook of the Promise, this seems counter-intuitive. Wouldn't it be better to just include the _validateParams() call within the promise block so that an error thrown is handled in the promise's catch() hook?
Maybe you can add a property to the error thrown to indicate that it was a validation error.

**Comment by ianjuma** [comment]
I think @aksalj has this comment on promise itself, I've seen this a few times.

**Comment by jniles** [comment]
@ianjuma @aksalj was a decision reached about how this should be handled?  I could put in a PR for it.

**Comment by ianjuma** [comment]
Hi @jniles haven't looked at this; sure :dancer:

**Comment by aksalj** [comment]
@jniles please do! 🙈  I seem to have forgotten about this for some reason

**Comment by jniles** [comment]
Cool!  I'll take a look at this this afternoon.
