### ISSUE TITLE
Simpler USSD builder for complex menus

### ISSUE THREAD

**Issue by habbes** [AfricasTalkingLtd/africastalking-node.js#19]
Hello, the method for building USSD menus as shown in the docs (using a series of if/switch statements on the input) seems tedious and impractical in the case of complex nested menus.

I've written a simple library that is compatible with the Africastalking API to make this easier. It takes a different approach by treating each menu screen as state and the whole ussd session as state machine, and uses rules based on input values, regular expressions or functions to link two states.

Here's the [the library (ussd-menu-builder)](https://github.com/habbes/ussd-menu-builder). The library is usable but lacks unit tests and has an incomplete documentation. I intend to finish those up before pushing to npm.

I thought I'd share it with you guys. You probably won't add it to your official NodeJs library cause it maybe a bit opinionated, but you could use it when giving tutorials or other projects.

**Comment by ianjuma** [comment]
I think this would be great - we need all the helpers just to make this so easy. 

@calvinkarundu should this be built into the official node.js wrapper? What do you think?

Too many switches or if's can be tedious. Lets make this easy for others. Maybe a few edge cases we need to cater for; just to be sure the helper can work for everyone. But the beauty with this is someone always has a fallback. So i can't foresee a challenge.

**Comment by calvinkarundu** [comment]
I really like this, especially how much cleaner it makes the code. I think the official wrapper shouldn't have opinions on how to implement things but instead helpers like these should be very welcome. As @habbes says, we can use this library in tutorials and demo projects to demonstrate an easier way to build complex menu flows.

**Comment by ianjuma** [comment]
I think it should be; as helpers make it so easy. This won't stop the normal flow - so, it's still very optional. (the helpers). Or maybe as an external dependency - but why? let's just bundle it in.

If guys don't like; they have the normal flow option. (example mentioned above).

**Comment by aksalj** [comment]
> I think the official wrapper shouldn't have opinions on how to implement things

Absolutely agree with @calvinkarundu. So, I would recommend **NOT** to add this to the library but mention/use it in the documentation and tutorials.

**Comment by pbombo** [comment]
+1 on @calvinkarundu's thought. It would be great if it were a recommended way to build USSD applications. It's great attempt and tests will go a long way to convincing others.

**Comment by ianjuma** [comment]
@habbes maybe then push a PR with an updated README on this?
