### ISSUE TITLE
Use supertest to mock API responses

### ISSUE THREAD

**Issue by jniles** [AfricasTalkingLtd/africastalking-node.js#22]
The test suite in `npm test` currently does not validate that the responses are handled for all libraries.  Only the USSD API makes use of the `supertest` server to mock API responses.  This ought to be extended to all libraries.  From what I can tell, the following libraries need API response testing:
- [ ] SMS
- [ ] Account
- [ ] Airtime
- [x] USSD

It doesn't look like the `voice.js` or `payment.js` libraries are tested.

**Comment by aksalj** [comment]
As the library user, do I really need to know much about AfricasTalking http responses when doing this?
```javascript
sms.send(opts)
       .then(success)
       .catch(error); // It should not matter where the error comes from, HTTP or not, right?
```
It makes sense for `USSD` because of the http callback.

@ianjuma What do you think?

**Comment by jniles** [comment]
The tests wouldn't be for the library user, they would be for the library itself.  The idea is that
```
sms.send(opts)
     .then(success)
     .catch(error)
```
should always catch errors when they are rejected by the API.

The inspiration for this proposal is taken from tests for other telephone HTTP APIs.  See for example [nexmo-node](https://github.com/Nexmo/nexmo-node/blob/master/test/CallResource-test.js).

Alternatively, [Twilio's tests](https://github.com/twilio/twilio-node/blob/master/spec/client.pricing.spec.js) use spies to check on the outgoing HTTP requests rather than mocked responses.  Since `supertest` is already a dependency, it seems natural to leverage it.

**Comment by aksalj** [comment]
👍 👍
