### ISSUE TITLE
401 on sandbox

### ISSUE THREAD

**Issue by clarkritchie** [AfricasTalkingLtd/africastalking-node.js#29]
Hi,

I just upgraded from 0.0.2 to 0.0.9 so that I can use the sandbox.

When I instrument my app using my production API account + key, it works great:
```
c2-dev-6 { username: 'ABC',
c2-dev-6   apiKey: 'XXX',
c2-dev-6   format: 'json',
c2-dev-6   sandbox: 'false' }
```

But when I instrument my app using my sandbox API account + key, I get 401 when I send a message:

```
c2-dev-7 { username: 'ABC',
c2-dev-7   apiKey: 'YYY',
c2-dev-7   format: 'json',
c2-dev-7   sandbox: true }
```

Any thoughts?  I've tried passing true as both as a string and boolean.

**Comment by clarkritchie** [comment]
I think this is an issue on their end, as I get error when I use their basic example with CURL.
```
curl -X GET 'https://api.africastalking.com/restless/send?username=ABC&Apikey=YYY&to=+1ZZZ&message=Hello'
```

**Comment by clarkritchie** [comment]
I ended up having to regenerate my sandbox key a good 5 or 6 times before the sandbox env would stop giving me 401.  :persevere:

**Comment by clarkritchie** [comment]
Still getting 401 even after switching to a known-good sandbox key, e.g. I can do it from CURL without issue.

**Comment by clarkritchie** [comment]
I still don't have it working but I think the 401 issue was due to a module that I'm using which was pinned to 0.0.5.  I changed that to 0.0.9 and I no longer see 401.  (However I also don't see it in my logs on sandbox...)

**Comment by inacali** [comment]
Hi am facing similar issue can you advice which module is causing this?

**Comment by calvinkarundu** [comment]
When developing on the sandbox environment, please use `sandbox` as the application username. We switched to this pattern about a [month ago](https://blog.africastalking.com/introducing-account-management-c7533d74cc8e). The authentication params become `username: "sandbox"` and in your header object `apikey: "your-sandbox-api-key"`.

I should also mention that whenever you update your apikey, the new key doesn't take effect immediately, instead, it will take effect in 5 minutes or less.
