### ISSUE TITLE
Airtime Implementation

### ISSUE THREAD

**Issue by habbes** [AfricasTalkingLtd/africastalking-node.js#3]
Hello, I would like to use the airtime API but noticed it's not yet implemented. I would like to add the implementation and make a pull request if you don't mind.

I'm going to implement the `airtime.send(options)` as shown in the repository doc.

Do you have any coding guide or convention I ought to follow?

**Comment by ianjuma** [comment]
yeah sure. Go ahead :+1:  :dancer:  We don't have a guideline for JS, we don't use JS internally - but I'd always go with the airbnb JS guidelines [Airbnb guide]( https://github.com/airbnb/javascript)

**Comment by habbes** [comment]
I made a pull request with the implementation #4

**Comment by ianjuma** [comment]
@habbes updated the README
