### ISSUE TITLE
Vulnerability Report

### ISSUE THREAD

**Issue by chinazor-allen** [AfricasTalkingLtd/africastalking-node.js#39]
I ran`npm audit` on my project and encountered the following vulnerabilities as seen in the image below; Is there a recommended plan to fix it? Maybe, you could run `npm audit` to view possible vulnerabilities and fixes.
![screen shot 2018-09-14 at 4 12 13 pm](https://user-images.githubusercontent.com/24938072/45568820-90733380-b855-11e8-8311-45d83de7705f.png)

**Comment by stonekase** [comment]
I think the fix for that will break the API, so it will take some time to fix this if one doesn't stay at the top of the matter.
