### ISSUE TITLE
The supplied authentication is invalid

### ISSUE THREAD

**Issue by raphaelchaula** [AfricasTalkingLtd/africastalking-node.js#45]
I use nextjs + express, It returns the same error titled above
I use your exact example

**Comment by Michaelmwirigi** [comment]
Hello. Please make sure you have created a file in your test folder called `fixtures.local` that has your username and apiKey from africastalking.

**Comment by raphaelchaula** [comment]
I have keys in .env, must I put them in fixtures.local
I texted it in a simple npm project it send messages pretty fine, in expressjs I keep getting the error

**Comment by Michaelmwirigi** [comment]
You don't have to put them in your fixtures.local. The example expects the variables from that file, unless you have changed that code.
So the sdk has no problem if it works in the first project, since the code used is the same. You'll need to share the expressjs code, so we can debug better.

The part with the problem is here;
`const options = {
    apiKey: 'YOUR_API_KEY',
    username: 'YOUR_USERNAME',
};
const AfricasTalking = require('africastalking')(options);
`

**Comment by raphaelchaula** [comment]
const smsOptions = {
  apiKey: 'my_key',
  username: 'my_app'
}
const AfricasTalking = require('africastalking')(smsOptions)
const sms = AfricasTalking.SMS

_ _ _

That is my smsOptions, is there any error noticiable?

**Comment by raphaelchaula** [comment]
AND HERE IS ALL MY CODE


const smsOptions = {
  apiKey: process.env.AFRICASTALKING_KEY,
  username: process.env.AFRICASTALKING_USERNAME
}
const AfricasTalking = require('africastalking')(smsOptions)

sms = AfricasTalking.SMS
var text = {
to: [req.body.telephone],
message: `Your JointPesa confirmation code is ${code}`
}
sms.send(text)
.then(response => {
  var payload = {
    userid: user._id,
    telephone: user.telephone
  }
  return res.status(200).json({
    message: 'user_created',
    token: jwt.sign(payload)
  })
})
.catch(error => {
  console.log(error)
  return res.status(500).json({
    message: error
  })
})

/ console.log(error) /
Gives "The supplied authentication is invalid"

**Comment by raphaelchaula** [comment]
HERE IS ALL MY CODE

const smsOptions = {
  apiKey: process.env.AFRICASTALKING_KEY,
  username: process.env.AFRICASTALKING_USERNAME
}
const AfricasTalking = require('africastalking')(smsOptions)

sms = AfricasTalking.SMS
var text = {
to: [req.body.telephone],
message: `Your confirmation code is ${code}`
}
sms.send(text)
.then(response => {
  var payload = {
    userid: user._id,
    telephone: user.telephone
  }
  return res.status(200).json({
    message: 'user_created',
    token: jwt.sign(payload)
  })
})
.catch(error => {
  console.log(error)
  return res.status(500).json({
    message: error
  })
})

/ console.log(error) /
Gives "The supplied authentication is invalid"

**Comment by Michaelmwirigi** [comment]
I have tested this code in an express app and the sms is sent, without a validation error. 
I have also tested it in our documentation, where you can write code and test from your browser. An example can be found [here](https://build.at-labs.io/course/5c80fe70b49fc00087d14ad5). start the course and test your code from there. 
I think the credentials may not be correct. Please also confirm the credentials used are correct.

**Comment by raphaelchaula** [comment]
In express app I get the error, in simple node app, sms is sent pretty fine, the same code.
The same credentials are used, I believe credentials are correct, I keep confirming them since yesterday.

**Comment by Michaelmwirigi** [comment]
Please log your `smsOptions` and make sure the username and apiKey used are correct.
Also check this [article](http://help.africastalking.com/en/articles/1036048-why-am-i-getting-the-error-supplied-authentication-is-invalid) on supplied authentication issues

**Comment by raphaelchaula** [comment]
The same problem, smsOptions log the correct options, I don't get it, The same code works fine and sends sms to sandbox now I am in live environement, authentication is invalid, do you use some urls or whatever that is dependent of expressjs eg. config etc

I think I should know that.

**Comment by Michaelmwirigi** [comment]
You've said this code works in sandbox but not in production? I am sure the credentials you are using are not correct, that is the error message you are getting after all. The same code used for sandbox is exactly the same as that of production, you don't need to set config for express. You only need to swap the username and apiKey used to the prod ones.
The article I sent earlier explains of the difference of the sandbox and the live environment.

**Comment by raphaelchaula** [comment]
I figured out the problem,
The error happens when I use graphql server (Apollo-server-express)
So the africastalking authentication isn't valid inside it, you guys need to test it and update your sdk
Thanks!

**Comment by aksalj** [comment]
Hey @raphaelchaula 
> ...the africastalking authentication isn't valid inside it
What do you mean by that?

**Comment by raphaelchaula** [comment]
I mean whenever you use Africastalking sdk inside Queries or Mutations of Apollo-server-express the authentication becomes invalid.

You can test it and figure out what might be the problem.

**Comment by aksalj** [comment]
This SDK simply `POST`s data and does not do any authentication... It could be that the value of either your app username or API key is changing before being sent by the SDK...

**Comment by DamianoSilverhand** [comment]
I am experiencing the same error , using the sandbox environment. I am using a node expess backend system,
Check my code below

From server.js:
`const express = require("express");
const router = express.Router();
const dotenv = require("dotenv");

dotenv.config();

// Get authentication
const credentials = {
  apiKey: process.env.apiKey, // use your sandbox app API key for development in the test environment
  username: process.env.username // use 'sandbox' for development in the test environment
};

const AfricasTalking = require("africastalking")(credentials);

const sms = AfricasTalking.SMS;
// Send SMS route
router.post("/", (req, res) => {
  const { to, message } = req.body || res.status(400).json({error: "Both 'to' and 'message' are required"});
  sms
    .send({ to, message, enque: true })
    .then(response => {
      console.log(response);
      res.json(response);
    })
    .catch(error => {
      console.log(error);
      res.json(error.toString());
    });
});

module.exports = router;`

app.js :
`const express = require("express");
const dotenv = require("dotenv");
const smsRoute = require("./server");
const bodyParser = require("body-parser");

dotenv.config();

const app = express();
const PORT = process.env.PORT || 8080;

app.listen(PORT, () => console.log(`running on localhost:${PORT}`));

app.use(bodyParser.json());

app.use("/", smsRoute);`

After posting the necessary data , to and message to the route, I get a "data: 'The supplied authentication is invalid' " error. I have tried regenerating  the sandbox api key but still getting the same error. I also tried sending the data direct from postman by setting the necessary header for api key and sending the data in the correct format but even there I get the same error. What can be done to sort this one?

**Comment by edwinnambaje** [comment]
> I am experiencing the same error , using the sandbox environment. I am using a node expess backend system, Check my code below
> 
> From server.js: `const express = require("express"); const router = express.Router(); const dotenv = require("dotenv");
> 
> dotenv.config();
> 
> // Get authentication const credentials = { apiKey: process.env.apiKey, // use your sandbox app API key for development in the test environment username: process.env.username // use 'sandbox' for development in the test environment };
> 
> const AfricasTalking = require("africastalking")(credentials);
> 
> const sms = AfricasTalking.SMS; // Send SMS route router.post("/", (req, res) => { const { to, message } = req.body || res.status(400).json({error: "Both 'to' and 'message' are required"}); sms .send({ to, message, enque: true }) .then(response => { console.log(response); res.json(response); }) .catch(error => { console.log(error); res.json(error.toString()); }); });
> 
> module.exports = router;`
> 
> app.js : `const express = require("express"); const dotenv = require("dotenv"); const smsRoute = require("./server"); const bodyParser = require("body-parser");
> 
> dotenv.config();
> 
> const app = express(); const PORT = process.env.PORT || 8080;
> 
> app.listen(PORT, () => console.log(`running on localhost:${PORT}`));
> 
> app.use(bodyParser.json());
> 
> app.use("/", smsRoute);`
> 
> After posting the necessary data , to and message to the route, I get a "data: 'The supplied authentication is invalid' " error. I have tried regenerating the sandbox api key but still getting the same error. I also tried sending the data direct from postman by setting the necessary header for api key and sending the data in the correct format but even there I get the same error. What can be done to sort this one?

Simply change app.use(bodyParser.json()); to app.use(express.json()); and it should work as expected
