### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by DavidAmunga** [AfricasTalkingLtd/africastalking-node.js#46]
Will there be possible support for TypeScript in the future ? Also are PR's welcome from non-employees ?

**Comment by aksalj** [comment]
Hey @DavidAmunga PRs are welcome!

**Comment by auderephilip** [comment]
@aksalj & @DavidAmunga : indeed - came here just to ask this.  Looking forward to TypeScript support.  Thank you both!

**Comment by iampato** [comment]
Why close it ....at least provide a .d.ts file then ???
