### ISSUE TITLE
setup git hooks on npm

### ISSUE THREAD

**Issue by ianjuma** [AfricasTalkingLtd/africastalking-node.js#5]
@aksalj can we setup git hooks on npm; to update the package and version on a git push?

**Comment by aksalj** [comment]
Maybe we update the package when we create a [**release**](https://developer.github.com/v3/activity/events/types/#releaseevent) on Github; People (`me`) some times push unfinished code, we wouldn't want to break other people's code :sob:

**Comment by ianjuma** [comment]
Yes, we can do a release event - that should work fine.
