### ISSUE TITLE
Airtime Error in customAxios folder: ...data

### ISSUE THREAD

**Issue by Leeibrah** [AfricasTalkingLtd/africastalking-node.js#67]
Hello Africastalking,

I am having an issue with my node application which gives me the error: 

/var/www/server/node_modules/africastalking/lib/customAxios/airtime.js:7
                ...data,
                ^^^
SyntaxError: Unexpected token ...

I think it refers to the three dots before the variable data.

How can this be solved because it runs okay on my localhost but when I try to run it on the server it gives me the said error.

Thank you.

**Comment by aksalj** [comment]
Most likely running node 4 or older on your server...
