### ISSUE TITLE
Security Venerability

### ISSUE THREAD

**Issue by Ikxyz** [AfricasTalkingLtd/africastalking-node.js#75]
We have been using the SDK for quite a while now, but of recent some real **security issues** has been popping up due to some **outdated dependencies** within the **grpc** dependency SDK 

Below are list of vulnerable dependencies in **grpc**:

1. mime  
2. hoek
3. tunnel-agent
4. minimist
5. cryptiles

![Screen Shot 2020-05-31 at 5 20 02 AM](https://user-images.githubusercontent.com/40415727/83344458-17549200-a2ff-11ea-9aa5-1ee85d83898f.png)

**Please** I urge you guys to investigate the above-listed dependencies which require urgent update due to the **severity** of the **vulnerability**

**Comment by crispinkoech** [comment]
Hey @Ikxyz thanks for raising this issue with us. Looking into it :+1:
