### ISSUE TITLE
High vulnerability with cryptiles@2.x.x

### ISSUE THREAD

**Issue by kulemantu** [AfricasTalkingLtd/africastalking-node.js#82]
![image](https://user-images.githubusercontent.com/907164/88266685-47555b80-ccd8-11ea-9d06-99abd391774c.png)

High vulnerability with `unirest -> hawk -> cryptiles`. If this is something we think won't break if we upgrade, can submit the pull request. Any info before I attempt that?

**Comment by tawn33y** [comment]
@zlyxero I think you are best placed to advise on the `unirest` issue?

**Comment by kulemantu** [comment]
I resolved this by running `npm audit fix`. Would still be good to fix these on your side and reupload the new package.
