### ISSUE TITLE
Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by elvisAR-git** [AfricasTalkingLtd/africastalking-node.js#83]
Hello, i really wanna learn to use your api, but i cant get over this one stubborn error. what i'm i doing wrong?

**Comment by tawn33y** [comment]
Hi @elvisAR-git 

Can you kindly elaborate? Can you share the complete error stack?

If possible, please also provide screenshots and/or code samples to be able to pinpoint the source of the error.

**Comment by elvisAR-git** [comment]
I will, soon. Thank you for responding.
