### ISSUE TITLE
send different messages to different numbers simultaneously ?

### ISSUE THREAD

**Issue by lubegasimon** [AfricasTalkingLtd/africastalking-node.js#84]
For one of my project, I want to send different messages to different numbers simultaneously, for instance,
when a loan is given out, a message (`you have recieved a loan of <some amount> from person X` is sent to the `borrower`, and another sent to the lender (`You have sent <some amount> to person Y`).
But africastalking seems not to have that options

What I propose could enable such flexibility;
```
import AfricasTalking from "africastalking";

const africasTalking = new AfricasTalking({
  username: "sandbox",
  apiKey: process.env.AFRICA_TALKING_KEY
});

const sms = africasTalking.SMS;

...

  sms.send([
   {
    to: phone1,
    message: `message to ${recipient1}.`
   },
   {
     to: phone2,
    message: `message to ${recipient2}.`
   }
  ])

...

```
what `africastalking` accepts;

```
  sms.send(
   {
    to: phone1,
    message: `message to ${recipient1}.`
   }
 )
```

**Comment by crispinkoech** [comment]
Hey @lubegasimon for this, we could wire a separate function, something like `sendMultiple()` which would take the parameters you've provided, but the underlying code would still utilize `sms.send()`. Would this work for you?

**Comment by aksalj** [comment]
I like @lubegasimon's suggestion; the `send()` function can simply check if it was given an array or a single item, and proceed the same way it is doing currently...
