### ISSUE TITLE
The supplied authentication is invalid

### ISSUE THREAD

**Issue by aifodu** [AfricasTalkingLtd/africastalking-node.js#88]
I am using "africastalking": "^0.5.3"

With sandbox username and API Keys, I am able to send SMS. But when I swap the credentials to LIVE DATA, it returns _The supplied authentication is invalid_

Reverting back to SANDBOX environment data works well.

**Comment by EKibet** [comment]
@aifodu how did you work around this issue?

**Comment by aifodu** [comment]
I hope by now you have been able to resolve this @EKibet. My problem had to do with my auth credentials, I wasn't using it correctly. 
PS: I'd be glad to help if you are still having this issue.
