### ISSUE TITLE
Installing africastalking using npm not working

### ISSUE THREAD

**Issue by kamalafidele** [AfricasTalkingLtd/africastalking-node.js#92]

**Comment by frankhn** [comment]
Had this issue as well, I wonder if these guys ever check this anyway????

**Comment by aksalj** [comment]
Hey @frankhn , can you share any error logs?

**Comment by frankhn** [comment]
Once you hit `npm install  --save africastalking`

it keeps on repeating this forever

`../deps/grpc/src/core/lib/gprpp/memory.h:119:37: warning: unused parameter 'n' [-Wunused-parameter]
  void deallocate(T* p, std::size_t n) { gpr_free(p); }
                                    ^
In file included from ../deps/grpc/src/core/lib/channel/channel_stack_builder.cc:21:
In file included from ../deps/grpc/src/core/lib/channel/channel_stack_builder.h:27:
In file included from ../deps/grpc/src/core/lib/channel/channel_stack.h:44:
../deps/grpc/src/core/lib/debug/trace.h:119:37: warning: unused parameter 'default_enabled' [-Wunused-parameter]
  constexpr DebugOnlyTraceFlag(bool default_enabled, const char* name) {}
                                    ^
../deps/grpc/src/core/lib/debug/trace.h:119:66: warning: unused parameter 'name' [-Wunused-parameter]
  constexpr DebugOnlyTraceFlag(bool default_enabled, const char* name) {}
                                                                 ^
../deps/grpc/src/core/lib/debug/trace.h:124:25: warning: unused parameter 'enabled' [-Wunused-parameter]
  void set_enabled(bool enabled) {}
                        ^
In file included from ../deps/grpc/src/core/lib/channel/channel_stack_builder.cc:21:
In file included from ../deps/grpc/src/core/lib/channel/channel_stack_builder.h:27:
In file included from ../deps/grpc/src/core/lib/channel/channel_stack.h:47:
In file included from ../deps/grpc/src/core/lib/iomgr/call_combiner.h:30:
../deps/grpc/src/core/lib/gprpp/ref_counted.h:83:59: warning: unused parameter 'trace_flag' [-Wunused-parameter]
  constexpr explicit RefCount(Value init = 1, TraceFlagT* trace_flag = nullptr)
                                                          ^
../deps/grpc/src/core/lib/gprpp/ref_counted.h:103:33: warning: unused parameter 'location' [-Wunused-parameter]
  void Ref(const DebugLocation& location, const char* reason, Value n = 1) {
                                ^
../deps/grpc/src/core/lib/gprpp/ref_counted.h:103:55: warning: unused parameter 'reason' [-Wunused-parameter]
  void Ref(const DebugLocation& location, const char* reason, Value n = 1) {
                                                      ^`

**Comment by frankhn** [comment]
@aksalj Trying this works at some point
 `npm i africastalking -S`
Don't know why tho

**Comment by aksalj** [comment]
What is your version of nodejs and which OS? I am trying to replicate the issue; but from that log, it's looking like one of the dependencies(`grpc`) is failing to build

**Comment by frankhn** [comment]
Node -v : `v15.10.0`
Mac OS

**Comment by aksalj** [comment]
@frankhn Unable to replicate the issue on `node 15.10.0` and `Mac OS 11.3.1` Can you try updating your xcode command line tools package?

**Comment by aksalj** [comment]
Or you could share the entire log to the point where it starts looping...

**Comment by LinusMuema** [comment]
Hi @aksalj 
I am facing the same issue even after trying the suggested solution.

The complete log:
[2022-01-28T09_11_36_656Z-debug-0.log](https://github.com/AfricasTalkingLtd/africastalking-node.js/files/7957320/2022-01-28T09_11_36_656Z-debug-0.log)

**Comment by aksalj** [comment]
Hey @LinusMuema, can you try using `v0.5.5-rc1`?
```
npm i africastalking@0.5.5-rc1
```
